[build]
providers = ["node"]

[phases.setup]
dependsOn = []
cmds = [
  "rm -rf lib/generated/prisma",
  "pnpm install --frozen-lockfile",
  "pnpm prisma generate"
]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "pnpm build"
]

[start]
cmd = "pnpm start"