[build]
providers = ["node"]

[phases.setup]
dependsOn = []
cmds = [
  "rm -rf lib/generated/prisma"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "pnpm install --frozen-lockfile --prefer-offline"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "pnpm build"
]

[start]
cmd = "pnpm start"